/**
 * ExtendScript Array standard-compatible polyfills.
 */

//@include "./Lib/arrayInternals.js"
//@include "./Lib/isArray.js"
//@include "./Lib/at.js"
//@include "./Lib/copyWithin.js"
//@include "./Lib/fill.js"
//@include "./Lib/entries.js"
//@include "./Lib/keys.js"
//@include "./Lib/values.js"
//@include "./Lib/every.js"
//@include "./Lib/some.js"
//@include "./Lib/forEach.js"
//@include "./Lib/map.js"
//@include "./Lib/filter.js"
//@include "./Lib/find.js"
//@include "./Lib/findIndex.js"
//@include "./Lib/findLast.js"
//@include "./Lib/findLastIndex.js"
//@include "./Lib/includes.js"
//@include "./Lib/indexOf.js"
//@include "./Lib/lastIndexOf.js"
//@include "./Lib/flat.js"
//@include "./Lib/flatMap.js"
//@include "./Lib/from.js"
//@include "./Lib/of.js"
//@include "./Lib/reduce.js"
//@include "./Lib/reduceRight.js"
//@include "./Lib/toReversed.js"
//@include "./Lib/toSorted.js"
//@include "./Lib/toSpliced.js"
//@include "./Lib/with.js"
